version: 2.1
jobs:
  Testing:
    docker:
      - image: pridecontrol/wdio-selenium-standalone:1.0.0
        auth:
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      - run:
          name: "Copy file to work directory"
          command: cp -r . /app/
      - run:
          name: "Install Selenium Standalone server"
          command: |
            cd /app/
            npm install install selenium-standalone
            npx selenium-standalone install
            npx selenium-standalone start
          background: true
      - run:
          name: "Run test - Firefox"
          command: |
            cd /app/
            echo "BROWSER=firefox" > .env
            echo "HEADLESS=true" >> .env
            npm run test -- --suite "sanityTest"
          when: always

workflows:
  Test-Workflow:
    jobs:
      - Testing
